GET http://localhost:5295/games

###
GET http://localhost:5295/games/2


###
POST http://localhost:5295/games
Content-Type: application/json

{
  "name": "Call of Duty: Modern Warfare II",
  "genreId": 1,
  "price": 20.99,
  "releaseDate": "2019-11-02"
}

###
PUT http://localhost:5295/games/2
Content-Type: application/json

{
  "name": "Call of Duty: Black Ops Cold War",
  "genreId": 1,
  "price": 30.59,
  "releaseDate": "2019-11-02"
}

###
DELETE http://localhost:5295/games/5